site_name: LYHの博客
site_description: 学习笔记

theme:
  name: material
  language: zh
  
  # 调色板配置
  palette:
    - scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式
    
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  
  # 字体配置
  font:
    text: "Noto Sans SC"
    code: "Fira Code"
  
  # 图标配置
  icon:
    repo: fontawesome/brands/github
  
  # 功能特性
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# 导航配置应该在这里，与theme同级！
nav:
  - 首页: index.md
  - 学习资料:
    - 级数: 级数.md
    - 算法笔记: 算法笔记.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
